FROM rust:1.74-bookworm AS builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y musl-tools
RUN rustup target add "$(uname -m)"-unknown-linux-musl
RUN cargo build --bin get_metadata --release --target "$(uname -m)"-unknown-linux-musl
RUN strip /app/target/"$(uname -m)"-unknown-linux-musl/release/get_metadata -o /get_metadata

FROM scratch
COPY --from=builder /get_metadata /get_metadata
ENTRYPOINT ["/get_metadata"]
