FROM rust:1.74-bookworm AS builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y musl-tools
RUN rustup target add "$(uname -m)"-unknown-linux-musl
RUN cargo build --bin img2epub --release --target "$(uname -m)"-unknown-linux-musl
RUN strip /app/target/"$(uname -m)"-unknown-linux-musl/release/img2epub -o /img2epub

FROM scratch
COPY --from=builder /img2epub /img2epub
ENTRYPOINT ["/img2epub"]
