FROM rust:1.74-bookworm AS builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y musl-tools
RUN rustup target add "$(uname -m)"-unknown-linux-musl
RUN cargo build --bin gen_metadata --release --target "$(uname -m)"-unknown-linux-musl
RUN strip /app/target/"$(uname -m)"-unknown-linux-musl/release/gen_metadata -o /gen_metadata

FROM scratch
COPY --from=builder /gen_metadata /gen_metadata
ENTRYPOINT ["/gen_metadata"]
