version: "3"

env:
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/epubapi"
  IMAGES_BUCKET: "images-bucket"
  EPUB_BUCKET: "epub-bucket"
  OUT_IMAGES_BUCKET: "out-images-bucket"
  S3_ENDPOINT: "http://localhost:9000"
  PUBLIC_S3_ENDPOINT: "http://localhost:9000"
  ADMIN_ID: "test_admin_id"
  ADMIN_PASSWORD: "test_admin_password"
  JWT_SECRET: "jwt_secret"
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: minio123

tasks:
  default:
    cmds:
      - task: all

  install:docker:
    cmds:
      - brew update
      - brew install docker docker-compose
      - mkdir -p $HOME/.docker/cli-plugins
      - ln -sfn /usr/local/opt/docker-compose/bin/docker-compose $HOME/.docker/cli-plugins/docker-compose
      - curl -LO $(brew --prefix lima)/bin/limactl "https://github.com/mikekazakov/lima-nohvf/raw/master/limactl"
      - sudo mv limactl $(brew --prefix lima)/bin/limactl
      - sudo chmod +x $(brew --prefix lima)/bin/limactl
      - colima start --network-address --arch arm64 --vm-type qemu

  install:sqlx-cli:
    cmds:
      - cargo install sqlx-cli --no-default-features --features native-tls,postgres
  
  install:julia:
    cmds:
      - curl -fsSL https://install.julialang.org | sh -s -- -y
      - $HOME/.juliaup/bin/julia -e 'using Pkg; Pkg.add("Plots"); Pkg.add("Metal")'
      - echo 'export PATH="$HOME/.juliaup/bin:$PATH"' >> $HOME/.zshrc

  ci:prepare:
    cmds:
      - mkdir -p ${HOME}/.local/bin

  ci:
    env:
      DOCKER_HOST: unix://$HOME/.lima/default/sock/docker.sock
    cmds:
      - task: install:docker
      - task: install:sqlx-cli
      - task: install:julia
      - zsh -c ". $HOME/.zshrc && cd test_assets && julia gen_test_data.jl"
      - docker compose down
      - docker compose up --build -d minio postgres
      - docker compose up --build create_bucket
      - cargo build
      - cargo sqlx prepare --database-url ${DATABASE_URL}
      - cargo run --bin gen_schema > openapi.json
      - cargo run --bin img2epub
      - cargo run --bin get_metadata
      - cargo run --bin epub2img
      - cargo test

  serve:
    cmds:
      - task: up
      - task: run

  schema:
    cmds:
      - cargo run --bin gen_schema > openapi.json

  test:
    cmds:
      - cargo test

  rebuild:
    cmds:
      - zsh -c ". $HOME/.zshrc && cd test_assets && julia gen_test_data.jl"
      - docker compose down
      - task: up

  up:
    cmds:
      - docker compose up --build -d minio postgres
      - docker compose up --build create_bucket
      - cargo build
      - task: sqlx
      - task: schema

  run:
    cmds:
      - cargo run

  sqlx:
    cmds:
      - cargo sqlx prepare --database-url ${DATABASE_URL}

  check:
    cmds:
      - task: sqlx
      - cargo check
      - task: schema

  all:
    cmds:
      - task: rebuild
      - cargo run --bin img2epub
      - cargo run --bin get_metadata
      - cargo run --bin epub2img
      - task: test

  tmp:
    cmds:
      - cargo run --bin epub2img
